rem openscad -D doitem=\"inner_base\"      -o jar-inner_base.stl        jar.scad
rem openscad -D doitem=\"inner_cap\"       -o jar-inner_cap.stl         jar.scad
rem openscad -D doitem=\"inner_post\"      -o jar-inner_post.stl        jar.scad
rem openscad -D doitem=\"inner_base_foot\" -o jar-inner_base_foot.stl   jar.scad
rem openscad -D doitem=\"inner_base_ring\" -o jar-inner_base_ring.stl   jar.scad
rem openscad -D doitem=\"outer_base_n\"    -o jar-outer_base_n.stl      jar.scad
rem openscad -D doitem=\"outer_base_e\"    -o jar-outer_base_e.stl      jar.scad
rem openscad -D doitem=\"outer_base_s\"    -o jar-outer_base_s.stl      jar.scad
rem openscad -D doitem=\"outer_base_w\"    -o jar-outer_base_w.stl      jar.scad
rem openscad -D doitem=\"outer_led_cover\" -o jar-outer_led_cover.stl   jar.scad
rem openscad -D doitem=\"inner_led_cover\" -o jar-inner_led_cover.stl   jar.scad
rem openscad -D doitem=\"testring_in\"     -o jar-testring_in.stl       jar.scad
rem openscad -D doitem=\"testring_out\"    -o jar-testring_out.stl      jar.scad
rem openscad -D doitem=\"spanner25\"       -o jar-spanner25.stl         jar.scad
rem openscad -D doitem=\"spanner14\"       -o jar-spanner14.stl         jar.scad
rem openscad -D doitem=\"brain_right\"     -o jar-brain_right.stl       jar.scad
rem openscad -D doitem=\"brain_left\"      -o jar-brain_left.stl        jar.scad
openscad -D doitem=\"outer_foot\"      -o jar-outer_foot.stl        jar.scad
openscad -D doitem=\"outer_foot_stem\" -o jar-outer_foot_stem.stl   jar.scad
