rem openscad -D doitem=\"outside_corner\" -o tht-outside_corner.stl theater.scad
rem openscad -D doitem=\"inside_corner\" -o tht-inside_corner.stl theater.scad
rem openscad -D doitem=\"top_corner\" -o tht-top_corner.stl theater.scad
rem openscad -D doitem=\"top_back\" -o tht-top_back.stl theater.scad
rem openscad -D doitem=\"top_front\" -o tht-top_front.stl theater.scad
rem openscad -D doitem=\"top_front_m\" -o tht-top_front_m.stl theater.scad
rem openscad -D doitem=\"topfront_pin\" -o tht-topfront_pin.stl theater.scad
rem openscad -D doitem=\"tc_jig\" -o tht-tc_jig.stl theater.scad

rem openscad -D doitem=\"front_cover\" -o tht-switch_cover.stl theaterv2.scad
rem openscad -D doitem=\"switch_shim\" -o tht-switch_shim.stl theaterv2.scad
rem openscad -D doitem=\"side_wall\" -o tht-side_wall.stl theaterv2.scad
rem openscad -D doitem=\"post_sleeve\" -o tht-post_sleeve.stl theaterv2.scad
rem openscad -D doitem=\"post_sleeve_bl\" -o tht-post_sleeve-bl.stl theaterv2.scad
rem openscad -D doitem=\"post_sleeve_tl\" -o tht-post_sleeve-tl.stl theaterv2.scad
rem openscad -D doitem=\"post_sleeve_tr\" -o tht-post_sleeve-tr.stl theaterv2.scad
rem openscad -D doitem=\"front_top_l\" -o tht-front_top-l.stl theaterv2.scad
rem openscad -D doitem=\"front_top_r\" -o tht-front_top-r.stl theaterv2.scad
openscad -D doitem=\"rod_holder\" -o tht-rod_holder.stl theaterv2.scad
